#!/usr/bin/python3
import random
number = random.randint(-10000, 10000)
if number < 0:
    new_number = -number
    last_digit = new_number % 10
    last_digit = -last_digit
    message = f"Last digit of {number} is {last_digit}"
    if last_digit > 5:
        print(message, "and is greater than 5")
    if last_digit == 0:
        print(message, "and is 0")
    elif last_digit < 6 and last_digit != 0:
        print(message, "and is less than 6 and not 0")
else:
    last_digit = number % 10
    message = f"Last digit of {number} is {last_digit}"
    if last_digit > 5:
        print(message, "and is greater than 5")
    if last_digit == 0:
        print(message, "and is 0")
    elif last_digit < 6 and last_digit != 0:
        print(message, "and is less than 6 and not 0")
